class Surah {
  final int number;
  final String arabicName;
  final String englishName;
  final int ayahCount;

  const Surah({
    required this.number,
    required this.arabicName,
    required this.englishName,
    required this.ayahCount,
  });
}


class Qurandate {

  static final List<Surah> getAllSurahs = [
    Surah(
      number: 1,
      arabicName: "الفاتحه",
      englishName: "Al-Fatiha",
      ayahCount: 7,
    ),
    Surah(
      number: 2,
      arabicName: "البقرة",
      englishName: "Al-Baqarah",
      ayahCount: 286,
    ),
    Surah(
      number: 3,
      arabicName: "آل عمران",
      englishName: "Aal-E-Imran",
      ayahCount: 200,
    ),
    Surah(
      number: 4,
      arabicName: "النساء",
      englishName: "An-Nisa'",
      ayahCount: 176,
    ),
    Surah(
      number: 5,
      arabicName: "المائدة",
      englishName: "Al-Ma'idah",
      ayahCount: 120,
    ),
    Surah(
      number: 6,
      arabicName: "الأنعام",
      englishName: "Al-An'am",
      ayahCount: 165,
    ),
    Surah(
      number: 7,
      arabicName: "الأعراف",
      englishName: "Al-A'raf",
      ayahCount: 206,
    ),
    Surah(
      number: 8,
      arabicName: "الأنفال",
      englishName: "Al-Anfal",
      ayahCount: 75,
    ),
    Surah(
      number: 9,
      arabicName: "التوبة",
      englishName: "At-Tawbah",
      ayahCount: 129,
    ),
    Surah(number: 10, arabicName: "يونس", englishName: "Yunus", ayahCount: 109),
    Surah(number: 11, arabicName: "هود", englishName: "Hud", ayahCount: 123),
    Surah(number: 12, arabicName: "يوسف", englishName: "Yusuf", ayahCount: 111),
    Surah(
      number: 13,
      arabicName: "الرعد",
      englishName: "Ar-Ra'd",
      ayahCount: 43,
    ),
    Surah(
      number: 14,
      arabicName: "إبراهيم",
      englishName: "Ibrahim",
      ayahCount: 52,
    ),
    Surah(
      number: 15,
      arabicName: "الحجر",
      englishName: "Al-Hijr",
      ayahCount: 99,
    ),
    Surah(
      number: 16,
      arabicName: "النحل",
      englishName: "An-Nahl",
      ayahCount: 128,
    ),
    Surah(
      number: 17,
      arabicName: "الإسراء",
      englishName: "Al-Isra",
      ayahCount: 111,
    ),
    Surah(
      number: 18,
      arabicName: "الكهف",
      englishName: "Al-Kahf",
      ayahCount: 110,
    ),
    Surah(number: 19, arabicName: "مريم", englishName: "Maryam", ayahCount: 98),
    Surah(number: 20, arabicName: "طه", englishName: "Ta-Ha", ayahCount: 135),
    Surah(
      number: 21,
      arabicName: "الأنبياء",
      englishName: "Al-Anbiya",
      ayahCount: 112,
    ),
    Surah(
      number: 22,
      arabicName: "الحج",
      englishName: "Al-Hajj",
      ayahCount: 78,
    ),
    Surah(
      number: 23,
      arabicName: "المؤمنون",
      englishName: "Al-Mu'minun",
      ayahCount: 118,
    ),
    Surah(
      number: 24,
      arabicName: "النّور",
      englishName: "An-Nur",
      ayahCount: 64,
    ),
    Surah(
      number: 25,
      arabicName: "الفرقان",
      englishName: "Al-Furqan",
      ayahCount: 77,
    ),
    Surah(
      number: 26,
      arabicName: "الشعراء",
      englishName: "Ash-Shu'ara",
      ayahCount: 227,
    ),
    Surah(
      number: 27,
      arabicName: "النّمل",
      englishName: "An-Naml",
      ayahCount: 93,
    ),
    Surah(
      number: 28,
      arabicName: "القصص",
      englishName: "Al-Qasas",
      ayahCount: 88,
    ),
    Surah(
      number: 29,
      arabicName: "العنكبوت",
      englishName: "Al-Ankabut",
      ayahCount: 69,
    ),
    Surah(
      number: 30,
      arabicName: "الرّوم",
      englishName: "Ar-Rum",
      ayahCount: 60,
    ),
    Surah(
      number: 31,
      arabicName: "لقمان",
      englishName: "Luqman",
      ayahCount: 34,
    ),
    Surah(
      number: 32,
      arabicName: "السجدة",
      englishName: "As-Sajda",
      ayahCount: 30,
    ),
    Surah(
      number: 33,
      arabicName: "الأحزاب",
      englishName: "Al-Ahzab",
      ayahCount: 73,
    ),
    Surah(number: 34, arabicName: "سبأ", englishName: "Saba", ayahCount: 54),
    Surah(number: 35, arabicName: "فاطر", englishName: "Fatir", ayahCount: 45),
    Surah(number: 36, arabicName: "يس", englishName: "Ya-Sin", ayahCount: 83),
    Surah(
      number: 37,
      arabicName: "الصافات",
      englishName: "As-Saffat",
      ayahCount: 182,
    ),
    Surah(number: 38, arabicName: "ص", englishName: "Sad", ayahCount: 88),
    Surah(
      number: 39,
      arabicName: "الزمر",
      englishName: "Az-Zumar",
      ayahCount: 75,
    ),
    Surah(number: 40, arabicName: "غافر", englishName: "Ghafir", ayahCount: 85),
    Surah(
      number: 41,
      arabicName: "فصّلت",
      englishName: "Fussilat",
      ayahCount: 54,
    ),
    Surah(
      number: 42,
      arabicName: "الشورى",
      englishName: "Ash-Shura",
      ayahCount: 53,
    ),
    Surah(
      number: 43,
      arabicName: "الزخرف",
      englishName: "Az-Zukhruf",
      ayahCount: 89,
    ),
    Surah(
      number: 44,
      arabicName: "الدّخان",
      englishName: "Ad-Dukhan",
      ayahCount: 59,
    ),
    Surah(
      number: 45,
      arabicName: "الجاثية",
      englishName: "Al-Jathiya",
      ayahCount: 37,
    ),
    Surah(
      number: 46,
      arabicName: "الأحقاف",
      englishName: "Al-Ahqaf",
      ayahCount: 35,
    ),
    Surah(
      number: 47,
      arabicName: "محمد",
      englishName: "Muhammad",
      ayahCount: 38,
    ),
    Surah(
      number: 48,
      arabicName: "الفتح",
      englishName: "Al-Fath",
      ayahCount: 29,
    ),
    Surah(
      number: 49,
      arabicName: "الحجرات",
      englishName: "Al-Hujurat",
      ayahCount: 18,
    ),
    Surah(number: 50, arabicName: "ق", englishName: "Qaf", ayahCount: 45),
    Surah(
      number: 51,
      arabicName: "الذاريات",
      englishName: "Adh-Dhariyat",
      ayahCount: 60,
    ),
    Surah(
      number: 52,
      arabicName: "الطور",
      englishName: "At-Tur",
      ayahCount: 49,
    ),
    Surah(
      number: 53,
      arabicName: "النجم",
      englishName: "An-Najm",
      ayahCount: 62,
    ),
    Surah(
      number: 54,
      arabicName: "القمر",
      englishName: "Al-Qamar",
      ayahCount: 55,
    ),
    Surah(
      number: 55,
      arabicName: "الرحمن",
      englishName: "Ar-Rahman",
      ayahCount: 78,
    ),
    Surah(
      number: 56,
      arabicName: "الواقعة",
      englishName: "Al-Waqi'a",
      ayahCount: 96,
    ),
    Surah(
      number: 57,
      arabicName: "الحديد",
      englishName: "Al-Hadid",
      ayahCount: 29,
    ),
    Surah(
      number: 58,
      arabicName: "المجادلة",
      englishName: "Al-Mujadila",
      ayahCount: 22,
    ),
    Surah(
      number: 59,
      arabicName: "الحشر",
      englishName: "Al-Hashr",
      ayahCount: 24,
    ),
    Surah(
      number: 60,
      arabicName: "الممتحنة",
      englishName: "Al-Mumtahina",
      ayahCount: 13,
    ),
    Surah(
      number: 61,
      arabicName: "الصف",
      englishName: "As-Saff",
      ayahCount: 14,
    ),
    Surah(
      number: 62,
      arabicName: "الجمعة",
      englishName: "Al-Jumu'a",
      ayahCount: 11,
    ),
    Surah(
      number: 63,
      arabicName: "المنافقون",
      englishName: "Al-Munafiqun",
      ayahCount: 11,
    ),
    Surah(
      number: 64,
      arabicName: "التغابن",
      englishName: "At-Taghabun",
      ayahCount: 18,
    ),
    Surah(
      number: 65,
      arabicName: "الطلاق",
      englishName: "At-Talaq",
      ayahCount: 12,
    ),
    Surah(
      number: 66,
      arabicName: "التحريم",
      englishName: "At-Tahrim",
      ayahCount: 12,
    ),
    Surah(
      number: 67,
      arabicName: "الملك",
      englishName: "Al-Mulk",
      ayahCount: 30,
    ),
    Surah(
      number: 68,
      arabicName: "القلم",
      englishName: "Al-Qalam",
      ayahCount: 52,
    ),
    Surah(
      number: 69,
      arabicName: "الحاقة",
      englishName: "Al-Haqqah",
      ayahCount: 52,
    ),
    Surah(
      number: 70,
      arabicName: "المعارج",
      englishName: "Al-Ma'arij",
      ayahCount: 44,
    ),
    Surah(number: 71, arabicName: "نوح", englishName: "Nuh", ayahCount: 28),
    Surah(
      number: 72,
      arabicName: "الجن",
      englishName: "Al-Jinn",
      ayahCount: 28,
    ),
    Surah(
      number: 73,
      arabicName: "المزّمّل",
      englishName: "Al-Muzzammil",
      ayahCount: 20,
    ),
    Surah(
      number: 74,
      arabicName: "المدّثر",
      englishName: "Al-Muddathir",
      ayahCount: 56,
    ),
    Surah(
      number: 75,
      arabicName: "القيامة",
      englishName: "Al-Qiyamah",
      ayahCount: 40,
    ),
    Surah(
      number: 76,
      arabicName: "الإنسان",
      englishName: "Al-Insan",
      ayahCount: 31,
    ),
    Surah(
      number: 77,
      arabicName: "المرسلات",
      englishName: "Al-Mursalat",
      ayahCount: 50,
    ),
    Surah(
      number: 78,
      arabicName: "النبأ",
      englishName: "An-Naba'",
      ayahCount: 40,
    ),
    Surah(
      number: 79,
      arabicName: "النازعات",
      englishName: "An-Nazi'at",
      ayahCount: 46,
    ),
    Surah(number: 80, arabicName: "عبس", englishName: "Abasa", ayahCount: 42),
    Surah(
      number: 81,
      arabicName: "التكوير",
      englishName: "At-Takwir",
      ayahCount: 29,
    ),
    Surah(
      number: 82,
      arabicName: "الإنفطار",
      englishName: "Al-Infitar",
      ayahCount: 19,
    ),
    Surah(
      number: 83,
      arabicName: "المطفّفين",
      englishName: "Al-Mutaffifin",
      ayahCount: 36,
    ),
    Surah(
      number: 84,
      arabicName: "الإنشقاق",
      englishName: "Al-Inshiqaq",
      ayahCount: 25,
    ),
    Surah(
      number: 85,
      arabicName: "البروج",
      englishName: "Al-Buruj",
      ayahCount: 22,
    ),
    Surah(
      number: 86,
      arabicName: "الطارق",
      englishName: "At-Tariq",
      ayahCount: 17,
    ),
    Surah(
      number: 87,
      arabicName: "الأعلى",
      englishName: "Al-A'la",
      ayahCount: 19,
    ),
    Surah(
      number: 88,
      arabicName: "الغاشية",
      englishName: "Al-Ghashiyah",
      ayahCount: 26,
    ),
    Surah(
      number: 89,
      arabicName: "الفجر",
      englishName: "Al-Fajr",
      ayahCount: 30,
    ),
    Surah(
      number: 90,
      arabicName: "البلد",
      englishName: "Al-Balad",
      ayahCount: 20,
    ),
    Surah(
      number: 91,
      arabicName: "الشمس",
      englishName: "Ash-Shams",
      ayahCount: 15,
    ),
    Surah(
      number: 92,
      arabicName: "الليل",
      englishName: "Al-Lail",
      ayahCount: 21,
    ),
    Surah(
      number: 93,
      arabicName: "الضحى",
      englishName: "Ad-Duha",
      ayahCount: 11,
    ),
    Surah(
      number: 94,
      arabicName: "الشرح",
      englishName: "Ash-Sharh",
      ayahCount: 8,
    ),
    Surah(number: 95, arabicName: "التين", englishName: "At-Tin", ayahCount: 8),
    Surah(
      number: 96,
      arabicName: "العلق",
      englishName: "Al-Alaq",
      ayahCount: 19,
    ),
    Surah(
      number: 97,
      arabicName: "القدر",
      englishName: "Al-Qadr",
      ayahCount: 5,
    ),
    Surah(
      number: 98,
      arabicName: "البينة",
      englishName: "Al-Bayyina",
      ayahCount: 8,
    ),
    Surah(
      number: 99,
      arabicName: "الزلزلة",
      englishName: "Az-Zalzalah",
      ayahCount: 8,
    ),
    Surah(
      number: 100,
      arabicName: "العاديات",
      englishName: "Al-Adiyat",
      ayahCount: 11,
    ),
    Surah(
      number: 101,
      arabicName: "القارعة",
      englishName: "Al-Qari'a",
      ayahCount: 11,
    ),
    Surah(
      number: 102,
      arabicName: "التكاثر",
      englishName: "At-Takathur",
      ayahCount: 8,
    ),
    Surah(
      number: 103,
      arabicName: "العصر",
      englishName: "Al-Asr",
      ayahCount: 3,
    ),
    Surah(
      number: 104,
      arabicName: "الهمزة",
      englishName: "Al-Humazah",
      ayahCount: 9,
    ),
    Surah(
      number: 105,
      arabicName: "الفيل",
      englishName: "Al-Fil",
      ayahCount: 5,
    ),
    Surah(
      number: 106,
      arabicName: "قريش",
      englishName: "Quraysh",
      ayahCount: 4,
    ),
    Surah(
      number: 107,
      arabicName: "الماعون",
      englishName: "Al-Ma'un",
      ayahCount: 7,
    ),
    Surah(
      number: 108,
      arabicName: "الكوثر",
      englishName: "Al-Kawthar",
      ayahCount: 3,
    ),
    Surah(
      number: 109,
      arabicName: "الكافرون",
      englishName: "Al-Kafirun",
      ayahCount: 6,
    ),
    Surah(
      number: 110,
      arabicName: "النصر",
      englishName: "An-Nasr",
      ayahCount: 3,
    ),
    Surah(
      number: 111,
      arabicName: "المسد",
      englishName: "Al-Masad",
      ayahCount: 5,
    ),
    Surah(
      number: 112,
      arabicName: "الإخلاص",
      englishName: "Al-Ikhlas",
      ayahCount: 4,
    ),
    Surah(
      number: 113,
      arabicName: "الفلق",
      englishName: "Al-Falaq",
      ayahCount: 5,
    ),
    Surah(
      number: 114,
      arabicName: "الناس",
      englishName: "An-Nas",
      ayahCount: 6,
    ),
  ];
}